---
- name: check_install / Check firewalld status
  service_facts:
  no_log: true
  register: service_state

- name: check_install / Allow ports for firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop: "{{ zabbix_firewalld_port }}"
  when: service_state.ansible_facts.services['firewalld.service'].state == "running"