---
- name: install / Install Zabbix repository
  yum:
    name: https://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/7/x86_64/zabbix-release-{{ zabbix_release }}.el7.noarch.rpm
    state: present

- name: install / Clean yum cache
  command: yum clean all
  # warn: false

- name: install / Install Zabbix server, frontend, agent
  yum:
    name: "{{ zabbix_packages }}"
    state: present
    enablerepo: zabbix