---
postgres_firewalld_port: 5432
postgres_version: 12

postgres_mount_path: /opt/zabbix/data

db_name: zabbix
db_user: zabbix
db_password: zabbix

docker_req_packages:
  - yum-utils
  - device-mapper-persistent-data
  - lvm2

docker_compose_req_packages:
  - python-devel
  - gcc

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

docker_compose_version: 1.25.2