---
- name: Presetup / disable SELinux
  selinux:
    state: disabled
  register: result

- name: Presetup / server reboot
  reboot:
  when: result.reboot_required
  
- name: update yum packages
  yum:
    name: '*'
    state: latest
    update_cache: yes