---
- name: configure / disable SELinux
  selinux:
    state: disabled
  when: ansible_selinux.config_mode == "enforcing"

- name: update yum packages
  yum:
    name: '*'
    state: latest
    update_cache: yes