---
- name: install / Install docker-compose requirements
  yum:
    name: "{{ docker_compose_req_packages }}"
    state: latest

- name: install / Install docker compose
  pip:
    name: docker-compose
    state: latest
  no_log: true

- name: install / Check zabbix directory exist
  stat:
    path: /opt/zabbix
  register: zabbix_dir

- name: install / Make zabbix directory
  file:
    path: /opt/zabbix
    state: directory
    mode: "0777"
  when: zabbix_dir.stat.isdir is not defined