---
- name: install / Install postgresql-repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: install / Install PostgreSQL 12
  yum:
    name: postgresql12-server

- name: init database
  command: /usr/pgsql-12/bin/postgresql-12-setup initdb

- name: restart PostgreSQL
  systemd:
    name: postgresql-12
    state: restarted
    enabled: yes