---
- name: install / Install docker requirements
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: latest
  become: yes

- name: install / Install docker repo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  become: yes

- name: install / Install docker
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
  become: yes

- name: install / Start and enable docker service
  systemd:
    name: docker
    enabled: yes
    state: started
  become: yes

- name: install / Install compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.25.1/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: +x
  become: yes