---
- name: install / Check create.sql.gz file exist
  stat:
    path: /opt/zabbix/create.sql.gz
  register: init_db_file

- name: install / Copy create.sql.gz to postgres
  copy:
    src: /home/vagrant/ansible/roles/postgres/files/create.sql.gz
    dest: /opt/zabbix/
  when: not init_db_file.stat.exists

- name: check / Zabbix database is exists
  command: docker exec "{{ postgres_container_name }}" bash -c "psql -U zabbix -t zabbix"
  register: zabbix_db_result
  failed_when: false

# - name: install / Copy create.sql.gz to postgres container
#   command: docker cp /opt/zabbix/create.sql.gz "{{ postgres_container_name }}":/etc/create.sql.gz
#   when: not zabbix_db_result.stderr == ""

# - name: install / Initialize zabbix database
#   command: docker exec "{{ postgres_container_name }}" bash -c "zcat /etc/create.sql.gz | sudo -u zabbix psql zabbix"
#   when: not zabbix_db_result.stderr == ""

# - name: install / Copy pg_hba.conf
#   copy:
#     src: /home/vagrant/ansible/roles/postgres/files/pg_hba.conf
#     dest: /opt/zabbix/data