---
- name: install / Install epel-release
  yum:
    name: epel-release
    state: present

- name: install / Install Remi
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present

- name: install / Update all php dependencies
  yum:
    name: '*'
    enablerepo: remi-php71
    state: latest