---
- name: Setup Zabbix Server
  hosts: zabbix_servers
  become: true

  roles:
    - { role: common, tags: common }
    - { role: php, tags: php }
    # - { role: postgres, tags: posgres }
    # - { role: zabbix, tags: zabbix }